# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8c8019efd342345ffcbab980c4d430f9"
name = "format-suggestion"
handle = "format-suggestion"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "test-store-june.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
